import { dir } from "i18next";
import i18nConfig from "../../../i18nConfig";
import initTranslations from "@/i18n";
import TranslationsProvider from "../Component/TranslationProvider";
import Header from "../Component/Header";
import Footer from "../Component/Footer";
import { AuthProvider } from "./utils/AuthContext";
import CookieConsentClient from "../Component/CookieConsent/CookieConsent";


export const metadata = {
  title: "Mukti Hospital",
  description: "Generated by create next app",
};

// This function generates static parameters for each locale
export async function generateStaticParams() {
  return i18nConfig.locales.map((locale) => ({ locale }));
}

// RootLayout component which will wrap your application with context providers
export default async function RootLayout({ children, params }) {
  const { locale } = params;
  // Setting text direction based on the locale (like "ltr" for English, "rtl" for Arabic)
  const direction = dir(locale ?? "en");
  const i18nNamespaces = ["home"];
  // Initialize translations for the specified locale and namespaces
  const { resources } = await initTranslations(locale, i18nNamespaces);

  return (
    <html lang={locale} dir={direction} suppressHydrationWarning>
      <head>
        {/* Optionally, you can add meta tags, analytics scripts, or other external resources */}
      </head>
      <body>
        <AuthProvider>
          <TranslationsProvider
            namespaces={i18nNamespaces}
            locale={locale}
            resources={resources}
          >
            <Header />
            {/* Use the CookieConsentClient component here */}
            <CookieConsentClient />
            {children}
            <Footer />
          </TranslationsProvider>
        </AuthProvider>
      </body>
    </html>
  );
}
